### ISSUE TITLE
sigpy version issue

### ISSUE THREAD

**Issue by XiaoWang-Github** [mikgroup/kspace_precond#1]
It seems that your sigpy version in the requirements.txt sigpy==0.1.14 is too old.
Therefore, some of the commands cannot run. For example, if I run the following command:

pdhg_app = mr.app.SenseRecon(
    ksp, mps, coord=coord, max_iter=max_iter, lamda=lamda,
    solver='PrimalDualHybridGradient', device=device, save_objective_values=True)

compiler will tell me that the keyword "solver" cannot be found.

**Comment by frankong** [comment]
Thanks for letting me know! I've updated the requirement to 0.1.21.
