### ISSUE TITLE
3D recon

### ISSUE THREAD

**Issue by XiaoWang-Github** [mikgroup/kspace_precond#2]
Hi Frank,  does your code support 3D reconstruction, or only 2D?   It seems that all example datasets are 2D.  Is that right?  Do you have any 3D datasets for us to try?

**Comment by frankong** [comment]
Hi-- there are 3D datasets available at:
https://zenodo.org/record/3647820
https://zenodo.org/record/3672170

The code supports 3D, but it will be much slower and take up a lot of memory.

**Comment by pengdada** [comment]
Hi, Frank, btw, can u provide a simple python script to use these data?
