### ISSUE TITLE
K Space Format

### ISSUE THREAD

**Issue by XiaoWang-Github** [mikgroup/kspace_precond#4]
Hi Frank,
In your code, do you organize your k-space array  as number of coil channels, number of repetitions, and number of readout points? The coordinate array has its shape arranged as number of repetitions, number of readout points and number of dimensions.  Is that right?

How can we use your code for k space measurements in the ISMRM format?  The k space measurements we have are arranged as "the number of columns,  the number of spokes, and the number of coils ". How do we convert this format into your format?

**Comment by frankong** [comment]
Hi--
The functions only require the first dimension to be the batch dimension, so in MRI, that's the number of coils.
The number of columns and spokes can be arbitrary as long as they are consistent between the k-space array and the coordinates.
So I think you can take a transpose of your k-space measurements and the coordinates, then it should be good.
