### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by pengdada** [mikgroup/kspace_precond#5]
we test your code using your 3d dataset, whis the problem as follows?
----------------------------------------------------------------------------------------------------

sigpy.version:  0.1.21
coord: shape= (41861, 711, 3) , dtype= float32
ksp: shape= (12, 41861, 711) , dtype= complex64

JsenseRecon: 100%
10/10 [00:12<00:00, 1.22s/it]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
D:\ProgramData\Anaconda3\lib\site-packages\sigpy\linop.py in apply(self, input)
     93         try:
---> 94             self._check_ishape(input)
     95             output = self._apply(input)

D:\ProgramData\Anaconda3\lib\site-packages\sigpy\linop.py in _check_ishape(self, input)
     65             if i2 != -1 and i1 != i2:
---> 66                 raise ValueError(
     67                     'input shape mismatch for {s}, got {input_shape}'.format(

ValueError: input shape mismatch for <[41861, 711]x[41861, 711]> Reshape * Sum * Multiply * NUFFTAdjoint Linop>, got (12, 41861, 711)

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-7-9e34781eb06d> in <module>
     52 mps = mr.app.JsenseRecon(ksp, device=device).run()
     53 
---> 54 cg_app = mr.app.SenseRecon(
     55     ksp, mps, coord=coord, device=device, lamda=lamda,
     56     max_iter=max_iter, save_objective_values=True)

D:\ProgramData\Anaconda3\lib\site-packages\sigpy\mri\app.py in __init__(self, y, mps, lamda, weights, tseg, coord, device, coil_batch_size, comm, show_pbar, transp_nufft, **kwargs)
     76             show_pbar = show_pbar and comm.rank == 0
     77 
---> 78         super().__init__(A, y, lamda=lamda, show_pbar=show_pbar, **kwargs)
     79 
     80 

D:\ProgramData\Anaconda3\lib\site-packages\sigpy\app.py in __init__(self, A, y, x, proxg, lamda, G, g, z, solver, max_iter, P, alpha, max_power_iter, accelerate, tau, sigma, rho, max_cg_iter, save_objective_values, show_pbar, leave_pbar)
    211 
    212         self.x_device = backend.get_device(self.x)
--> 213         self._get_alg()
    214         if self.save_objective_values:
    215             self.objective_values = [self.objective()]

D:\ProgramData\Anaconda3\lib\site-packages\sigpy\app.py in _get_alg(self)
    245                     'ConjugateGradient cannot have proxg specified.')
    246 
--> 247             self._get_ConjugateGradient()
    248         elif self.solver == 'GradientMethod':
    249             if self.G is not None:

D:\ProgramData\Anaconda3\lib\site-packages\sigpy\app.py in _get_ConjugateGradient(self)
    262         I = linop.Identity(self.x.shape)
    263         AHA = self.A.H * self.A
--> 264         AHy = self.A.H(self.y)
    265 
    266         if self.lamda != 0:

D:\ProgramData\Anaconda3\lib\site-packages\sigpy\linop.py in __call__(self, input)
    120 
    121     def __call__(self, input):
--> 122         return self.__mul__(input)
    123 
    124     def __mul__(self, input):

D:\ProgramData\Anaconda3\lib\site-packages\sigpy\linop.py in __mul__(self, input)
    129             return Compose([self, M])
    130         elif isinstance(input, backend.get_array_module(input).ndarray):
--> 131             return self.apply(input)
    132 
    133         return NotImplemented

D:\ProgramData\Anaconda3\lib\site-packages\sigpy\linop.py in apply(self, input)
     96             self._check_oshape(output)
     97         except Exception as e:
---> 98             raise RuntimeError('Exceptions from {}.'.format(self)) from e
     99 
    100         return output

RuntimeError: Exceptions from <[41861, 711]x[41861, 711]> Reshape * Sum * Multiply * NUFFTAdjoint Linop>.

**Comment by pengdada** [comment]
btw we attach our code as in follows:
#############################################

#%matplotlib notebook

import sigpy as sp
import sigpy.mri as mr
import sigpy.plot as pl
import matplotlib.pyplot as plt
import numpy as np

try:
    import mkl
    mkl.set_num_threads(1)
except:
    pass

print("sigpy.version: ", sp.__version__)

max_iter = 1 #30
lamda = 1

#brain_dir='data/brain/'
#phantom_dir='data/3d/1/'
phantom_dir='data/3d/2/'

ksp_file = phantom_dir + 'ksp.npy'
coord_file = phantom_dir + 'coord.npy'

# Choose computing device, Device(-1) specifies CPU, while others specify GPUs.,GPU requires installing cupy.
try:
    device = sp.Device(0)
except:
    device = sp.Device(-1)
#device = sp.Device(0)

xp = device.xp
device.use()

# Load datasets.
coord = xp.load(coord_file)
ksp = xp.load(ksp_file)
print("coord: shape=", coord.shape, ", dtype=", coord.dtype)
print("ksp: shape=", ksp.shape, ", dtype=", ksp.dtype)

#mps = mr.app.JsenseRecon(ksp, coord=coord, device=device).run()
mps = mr.app.JsenseRecon(ksp, device=device).run()


cg_app = mr.app.SenseRecon(
    ksp, mps, coord=coord, device=device, lamda=lamda,
    max_iter=max_iter, save_objective_values=True)
cg_img = cg_app.run()

pl.ImagePlot(cg_img)

**Comment by XiaoWang-Github** [comment]
The 3D dataset Peng referred to are the ones you provided here https://github.com/mikgroup/kspace_precond/issues/2

**Comment by pengdada** [comment]
another example of using L1WaveletRecon as in 
[dataset-2.zip](https://github.com/mikgroup/kspace_precond/files/5334333/dataset-2.zip)

**Comment by frankong** [comment]
Hi--
It seems like `coord` is not used in `JsenseRecon`? is there a reason for that?

**Comment by frankong** [comment]
If you are interested, there's a non-cartesian mri tutorial using sigpy here: https://github.com/mikgroup/sigpy-mri-tutorial

**Comment by XiaoWang-Github** [comment]
Hi Frank,
  When we use the coord, as in the following command:

     mps=mr.app.JsenseRecon(ksp,coord=coord,device=device).run()

  We receive the following error message:

Loading coordinate file
Loading kspace data file
(45120, 384, 3)
(20, 45120, 384)
JsenseRecon:   0%|                                                                                                                                                          | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "kspace_precond.py", line 56, in <module>
    mps = mr.app.JsenseRecon(ksp, coord=coord, device=device).run()
  File "/home/ch194925/miniconda3/envs/pytorch/lib/python3.8/site-packages/sigpy/app.py", line 85, in run
    self.alg.update()
  File "/home/ch194925/miniconda3/envs/pytorch/lib/python3.8/site-packages/sigpy/alg.py", line 63, in update
    self._update()
  File "/home/ch194925/miniconda3/envs/pytorch/lib/python3.8/site-packages/sigpy/alg.py", line 414, in _update
    self.min1()
  File "/home/ch194925/miniconda3/envs/pytorch/lib/python3.8/site-packages/sigpy/mri/app.py", line 325, in min_mps_ker
    self.A_mps_ker = linop.ConvImage(
  File "/home/ch194925/miniconda3/envs/pytorch/lib/python3.8/site-packages/sigpy/mri/linop.py", line 154, in ConvImage
    C = sp.linop.ConvolveFilter(R.oshape, img_ker,
  File "/home/ch194925/miniconda3/envs/pytorch/lib/python3.8/site-packages/sigpy/linop.py", line 1588, in __init__
    D, b, B, m, n, s, c_i, c_o, p = conv._get_convolve_params(
  File "/home/ch194925/miniconda3/envs/pytorch/lib/python3.8/site-packages/sigpy/conv.py", line 185, in _get_convolve_params
    raise ValueError('In valid mode, either data or filter must be '
ValueError: In valid mode, either data or filter must be at least as large as the other in every axis.

**Comment by XiaoWang-Github** [comment]
We are using a 3D dataset in the format of ISMRM. However, it seems that you code does not run and we receive the above error message.  The 2D datasets seem to be okay and the code runs.   Perhaps if you can show us a demo on how you recon a 3D dataset, that will be helpful.

-Xiao Wang

**Comment by XiaoWang-Github** [comment]
Thank you, Frank.  We think we figured out the bug in the code.  So I am going to close this issue.

**Comment by pengdada** [comment]
tks a lot for your help.

**Comment by frankong** [comment]
Great! You're welcome.
